name: Build iOS Flutter

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔥 Flutter correto
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.0

      # 🔥 Limpeza total
      - name: Flutter clean
        run: flutter clean

      # 🔥 Dependências
      - name: Get dependencies
        run: flutter pub get

      # 🔥 Corrige pods quebrados
      - name: Reset CocoaPods
        run: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock

      - name: Install Pods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS (no codesign clean)
  	run: |
          flutter clean
          flutter pub get
          flutter build ios --no-codesign

      # 📦 Artefato
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
